In [1]:
# Create your first MLP in Keras
import time
start = time.time()
from keras.models import Sequential
from keras.layers import Dense
import numpy
import pandas as pd

Using TensorFlow backend.


In [2]:
#!pip install keras
#!pip install tensorflow

In [2]:
# fix random seed for reproducibility
numpy.random.seed(7)

In [3]:
# load pima indians dataset
dataset = numpy.loadtxt("diabetes", delimiter=",")

In [4]:
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]


In [5]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])

In [7]:
# Fit the model
model.fit(X, Y, epochs=100, batch_size=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
768/768 [==============================] - 4s 5ms/step - loss: 2.2910 - acc: 0.6094
Epoch 2/100
768/768 [==============================] - 0s 189us/step - loss: 0.7640 - acc: 0.6458
Epoch 3/100
768/768 [==============================] - 0s 186us/step - loss: 0.7067 - acc: 0.6563
Epoch 4/100
768/768 [==============================] - 0s 187us/step - loss: 0.6751 - acc: 0.6680
Epoch 5/100
768/768 [==============================] - 0s 189us/step - loss: 0.6633 - acc: 0.6732
Epoch 6/100
768/768 [==============================] - 0s 189us/step - loss: 0.6385 - acc: 0.6966
Epoch 7/100
768/768 [==============================] - 0s 194us/step - loss: 0.6466 - acc: 0.6901
Epoch 8/100
768/768 [==============================] - 0s 197us/step - loss: 0.6231 - acc: 0.6862
Epoch 9/100
768/768 [==============================] - 0s 190us/step - loss: 0.6327 - acc: 0.6823
Epoch 10/100
768/768 [==============================] - 0s 187us/step - 

In [9]:
# evaluate the model
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

#print(model.feature_importances_) #use inbuilt class feature_importances of tree based classifiers
#plot graph of feature importances for better visualization
#feat_importances = pd.Series(model.feature_importances_, index=X.columns)
#feat_importances.nlargest(10).plot(kind='barh')
#plt.show()

768/768 [==============================] - 0s 29us/step

acc: 79.6875%


In [10]:
end = time.time()
print(end - start)

155.09008026123047


## 1. Implute

In [11]:
dataset = pd.read_csv('diabetes.csv')
import time
start = time.time()

In [12]:
median_bmi = dataset['BMI'].std()
dataset['BMI'] = dataset['BMI'].replace(
    to_replace=0, value=median_bmi)

median_bloodp = dataset['BloodPressure'].std()
dataset['BloodPressure'] = dataset['BloodPressure'].replace(
    to_replace=0, value=median_bloodp)

median_plglcconc = dataset['Glucose'].std()
dataset['Glucose'] = dataset['Glucose'].replace(
    to_replace=0, value=median_plglcconc)

median_skinthick = dataset['SkinThickness'].std()
dataset['SkinThickness'] = dataset['SkinThickness'].replace(
    to_replace=0, value=median_skinthick)

median_Insulin = dataset['Insulin'].std()
dataset['Insulin'] = dataset['Insulin'].replace(
    to_replace=0, value=median_Insulin)

median_DiabetesPedigreeFunction = dataset['DiabetesPedigreeFunction'].std()
dataset['DiabetesPedigreeFunction'] = dataset['DiabetesPedigreeFunction'].replace(
    to_replace=0, value=median_DiabetesPedigreeFunction)

median_Age = dataset['Age'].std()
dataset['Age'] = dataset['Age'].replace(
    to_replace=0, value=median_Age)

In [13]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6    148.0           72.0      35.000000  115.244002  33.6   
1            1     85.0           66.0      29.000000  115.244002  26.6   
2            8    183.0           64.0      15.952218  115.244002  23.3   
3            1     89.0           66.0      23.000000   94.000000  28.1   
4            0    137.0           40.0      35.000000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [14]:
dataset.to_csv("diabetes_impute_std.csv", index=False, encoding="utf-8")

In [15]:
dataset = numpy.loadtxt("diabetes_impute_std.txt", delimiter=",")

In [16]:
X = dataset[:,0:8]
Y = dataset[:,8]

In [17]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])

In [19]:
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
768/768 [==============================] - 1s 1ms/step - loss: 4.6899 - acc: 0.4740
Epoch 2/100
768/768 [==============================] - 0s 202us/step - loss: 0.8663 - acc: 0.5768
Epoch 3/100
768/768 [==============================] - 0s 215us/step - loss: 0.7361 - acc: 0.6081
Epoch 4/100
768/768 [==============================] - 0s 200us/step - loss: 0.6688 - acc: 0.6510
Epoch 5/100
768/768 [==============================] - 0s 208us/step - loss: 0.6327 - acc: 0.6810
Epoch 6/100
768/768 [==============================] - 0s 212us/step - loss: 0.6220 - acc: 0.6745
Epoch 7/100
768/768 [==============================] - 0s 203us/step - loss: 0.6111 - acc: 0.6797
Epoch 8/100
768/768 [==============================] - 0s 198us/step - loss: 0.5934 - acc: 0.7057
Epoch 9/100
768/768 [==============================] - 0s 212us/step - loss: 0.5882 - acc: 0.7018
Epoch 10/100
768/768 [==============================] - 0s 307us/step - loss: 0.6015 - acc: 0.6992
Epoch 11/100
768/768 

Epoch 83/100
768/768 [==============================] - 0s 203us/step - loss: 0.4874 - acc: 0.7539
Epoch 84/100
768/768 [==============================] - 0s 201us/step - loss: 0.4809 - acc: 0.7604
Epoch 85/100
768/768 [==============================] - 0s 189us/step - loss: 0.4867 - acc: 0.7630
Epoch 86/100
768/768 [==============================] - 0s 182us/step - loss: 0.4825 - acc: 0.7448
Epoch 87/100
768/768 [==============================] - 0s 201us/step - loss: 0.4814 - acc: 0.7656
Epoch 88/100
768/768 [==============================] - 0s 182us/step - loss: 0.4822 - acc: 0.7591
Epoch 89/100
768/768 [==============================] - 0s 183us/step - loss: 0.4788 - acc: 0.7539
Epoch 90/100
768/768 [==============================] - 0s 196us/step - loss: 0.4784 - acc: 0.7630
Epoch 91/100
768/768 [==============================] - 0s 169us/step - loss: 0.4770 - acc: 0.7630
Epoch 92/100
768/768 [==============================] - 0s 235us/step - loss: 0.4779 - acc: 0.7604
Epoch 93/1

In [20]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))
end = time.time()
print(end - start)

768/768 [==============================] - 0s 235us/step

acc: 77.0833%
26.31741428375244


## impute in PCA

In [21]:
from sklearn.decomposition import PCA
import numpy
start = time.time()
dataset = numpy.loadtxt("diabetes_impute_std.txt", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]

pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)

[[-15.46505896 -32.15983414]
 [-26.35415787  32.55551479]
 [-10.77178388 -61.45464328]
 ...
 [-23.77110352  -3.39778147]
 [-19.82236876  -8.06381502]
 [-24.98538077  25.04875082]]


In [22]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
768/768 [==============================] - 1s 1ms/step - loss: 0.7444 - acc: 0.6029
Epoch 2/100
768/768 [==============================] - 0s 274us/step - loss: 0.6416 - acc: 0.6497
Epoch 3/100
768/768 [==============================] - 0s 195us/step - loss: 0.6261 - acc: 0.6523
Epoch 4/100
768/768 [==============================] - 0s 195us/step - loss: 0.6204 - acc: 0.6510
Epoch 5/100
768/768 [==============================] - 0s 182us/step - loss: 0.6146 - acc: 0.6510
Epoch 6/100
768/768 [==============================] - 0s 195us/step - loss: 0.6161 - acc: 0.6510
Epoch 7/100
768/768 [==============================] - 0s 195us/step - loss: 0.6111 - acc: 0.6523
Epoch 8/100
768/768 [==============================] - 0s 215us/step - loss: 0.6203 - acc: 0.6510
Epoch 9/100
768/768 [==============================] - 0s 202us/step - loss: 0.6076 - acc: 0.6497
Epoch 10/100
768/768 [==============================] - 0s 182us/step - loss: 0.6080 - acc: 0.6523
Epoch 11/100
768/768 

Epoch 83/100
768/768 [==============================] - 0s 209us/step - loss: 0.5732 - acc: 0.7174
Epoch 84/100
768/768 [==============================] - 0s 221us/step - loss: 0.5767 - acc: 0.7018
Epoch 85/100
768/768 [==============================] - 0s 234us/step - loss: 0.5790 - acc: 0.7174
Epoch 86/100
768/768 [==============================] - 0s 247us/step - loss: 0.5783 - acc: 0.6979
Epoch 87/100
768/768 [==============================] - 0s 202us/step - loss: 0.5757 - acc: 0.6966
Epoch 88/100
768/768 [==============================] - 0s 221us/step - loss: 0.5756 - acc: 0.7122
Epoch 89/100
768/768 [==============================] - 0s 208us/step - loss: 0.5806 - acc: 0.7188
Epoch 90/100
768/768 [==============================] - 0s 208us/step - loss: 0.5785 - acc: 0.7148
Epoch 91/100
768/768 [==============================] - 0s 222us/step - loss: 0.5762 - acc: 0.7057
Epoch 92/100
768/768 [==============================] - 0s 208us/step - loss: 0.5731 - acc: 0.7083
Epoch 93/1

In [23]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

end = time.time()
print(end - start)

768/768 [==============================] - 0s 234us/step

acc: 70.4427%
22.270019054412842


## 2.impute & scaling

In [12]:
dataset = pd.read_csv('diabetes.csv')
start = time.time()


In [13]:
median_bmi = dataset['BMI'].std()
dataset['BMI'] = dataset['BMI'].replace(
    to_replace=0, value=median_bmi)

median_bloodp = dataset['BloodPressure'].std()
dataset['BloodPressure'] = dataset['BloodPressure'].replace(
    to_replace=0, value=median_bloodp)

median_plglcconc = dataset['Glucose'].std()
dataset['Glucose'] = dataset['Glucose'].replace(
    to_replace=0, value=median_plglcconc)

median_skinthick = dataset['SkinThickness'].std()
dataset['SkinThickness'] = dataset['SkinThickness'].replace(
    to_replace=0, value=median_skinthick)

median_Insulin = dataset['Insulin'].std()
dataset['Insulin'] = dataset['Insulin'].replace(
    to_replace=0, value=median_Insulin)

median_DiabetesPedigreeFunction = dataset['DiabetesPedigreeFunction'].std()
dataset['DiabetesPedigreeFunction'] = dataset['DiabetesPedigreeFunction'].replace(
    to_replace=0, value=median_DiabetesPedigreeFunction)

median_Age = dataset['Age'].std()
dataset['Age'] = dataset['Age'].replace(
    to_replace=0, value=median_Age)


y = dataset["Outcome"].copy()
x = dataset.drop("Outcome", axis=1)

from sklearn.preprocessing import MinMaxScaler as Scaler

scaler = Scaler()
scaler.fit(x)
train_set_scaled = scaler.transform(x)

datafram = pd.DataFrame(data=train_set_scaled)


#datafram.to_csv("diabetes_impute_scaling_std.csv", index=False, encoding="utf-8")

C:\Users\Nazmus Sakib\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [14]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(
    dataset, test_size=0.2, random_state=42)

train_set_labels = train_set["Outcome"].copy()
train_set = train_set.drop("Outcome", axis=1)

test_set_labels = test_set["Outcome"].copy()
test_set = test_set.drop("Outcome", axis=1)

In [15]:
from sklearn.preprocessing import MinMaxScaler as Scaler

scaler = Scaler()
scaler.fit(train_set)
train_set_scaled = scaler.transform(train_set)
test_set_scaled = scaler.transform(test_set)

df = pd.DataFrame(data=train_set_scaled)
df.head()

C:\Users\Nazmus Sakib\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


0         1         2         3         4         5         6  \
0  0.117647  0.311490  0.000000  0.144586  0.121688  0.000000  0.096499   
1  0.529412  0.479127  0.610304  0.290909  0.121688  0.343081  0.514091   
2  0.058824  0.640777  0.259578  0.200000  0.082933  0.351525  0.245944   
3  0.000000  0.772492  0.298548  0.144586  0.121688  0.236691  0.075149   
4  0.352941  0.610842  0.590820  0.527273  0.427885  0.647054  0.068318   

          7  
0  0.000000  
1  0.483333  
2  0.016667  
3  0.733333  
4  0.416667

In [16]:
df.to_csv("diabetes_impute_scaling.csv", index=False, encoding="utf-8")

In [25]:
dataset = numpy.loadtxt("diabetes_impute_scaling_std.txt", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]


model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [18]:
import eli5
from eli5.sklearn import PermutationImportance
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
768/768 [==============================] - 11s 14ms/step - loss: 0.4750 - acc: 0.7786
Epoch 2/100
768/768 [==============================] - 0s 200us/step - loss: 0.4802 - acc: 0.7656
Epoch 3/100
768/768 [==============================] - 0s 192us/step - loss: 0.4663 - acc: 0.7812
Epoch 4/100
768/768 [==============================] - 0s 220us/step - loss: 0.4707 - acc: 0.7865
Epoch 5/100
768/768 [==============================] - 0s 192us/step - loss: 0.4647 - acc: 0.7917
Epoch 6/100
768/768 [==============================] - 0s 412us/step - loss: 0.4625 - acc: 0.7721
Epoch 7/100
768/768 [==============================] - 0s 200us/step - loss: 0.4669 - acc: 0.7760
Epoch 8/100
768/768 [==============================] - 0s 171us/step - loss: 0.4746 - acc: 0.7630
Epoch 9/100
768/768 [==============================] - 0s 171us/step - loss: 0.4720 - acc: 0.7760
Epoch 10/100
768/768 [==============================] - 0s 159us/step - loss: 0.4681 - acc: 0.7839
Epoch 11/100
768/76

In [27]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

end = time.time()
print(end - start)

from mlxtend.feature_selection import SequentialFeatureSelector

feature_selector = SequentialFeatureSelector(Sequential()),
           k_features=8,
           forward=False,
           verbose=2,
           scoring='roc_auc',
           cv=4)

IndentationError: unexpected indent (<ipython-input-27-dcb943b3caa8>, line 10)

## impute&scaling PCA

In [35]:
from sklearn.decomposition import PCA
import numpy
start = time.time()
dataset = numpy.loadtxt("diabetes_impute_scaling_std.txt", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]

pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)

[[ 0.32848414  0.04767619]
 [-0.22643479 -0.10992424]
 [ 0.23699816  0.07104916]
 ...
 [-0.00726968 -0.08620371]
 [ 0.02014254 -0.02871416]
 [-0.27715052 -0.02236748]]


In [37]:
model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

Epoch 1/100
768/768 [==============================] - 2s 2ms/step - loss: 0.6181 - acc: 0.6549
Epoch 2/100
768/768 [==============================] - 0s 203us/step - loss: 0.5434 - acc: 0.7148
Epoch 3/100
768/768 [==============================] - 0s 224us/step - loss: 0.5166 - acc: 0.7448
Epoch 4/100
768/768 [==============================] - 0s 264us/step - loss: 0.5105 - acc: 0.7435
Epoch 5/100
768/768 [==============================] - 0s 203us/step - loss: 0.5074 - acc: 0.7539
Epoch 6/100
768/768 [==============================] - 0s 224us/step - loss: 0.5067 - acc: 0.7448
Epoch 7/100
768/768 [==============================] - 0s 224us/step - loss: 0.5059 - acc: 0.7552
Epoch 8/100
768/768 [==============================] - 0s 244us/step - loss: 0.5045 - acc: 0.7552
Epoch 9/100
768/768 [==============================] - 0s 264us/step - loss: 0.5036 - acc: 0.7526
Epoch 10/100
768/768 [==============================] - 0s 224us/step - loss: 0.5029 - acc: 0.7513
Epoch 11/100
768/768 

In [30]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))
end = time.time()
print(end - start)

768/768 [==============================] - 0s 346us/step

acc: 79.1667%
18.98348331451416


## impute & normalization

In [31]:
dataset = pd.read_csv('diabetes.csv')

start = time.time()
median_bmi = dataset['BMI'].std()
dataset['BMI'] = dataset['BMI'].replace(
    to_replace=0, value=median_bmi)

median_bloodp = dataset['BloodPressure'].std()
dataset['BloodPressure'] = dataset['BloodPressure'].replace(
    to_replace=0, value=median_bloodp)

median_plglcconc = dataset['Glucose'].std()
dataset['Glucose'] = dataset['Glucose'].replace(
    to_replace=0, value=median_plglcconc)

median_skinthick = dataset['SkinThickness'].std()
dataset['SkinThickness'] = dataset['SkinThickness'].replace(
    to_replace=0, value=median_skinthick)

median_Insulin = dataset['Insulin'].std()
dataset['Insulin'] = dataset['Insulin'].replace(
    to_replace=0, value=median_Insulin)

median_DiabetesPedigreeFunction = dataset['DiabetesPedigreeFunction'].std()
dataset['DiabetesPedigreeFunction'] = dataset['DiabetesPedigreeFunction'].replace(
    to_replace=0, value=median_DiabetesPedigreeFunction)

median_Age = dataset['Age'].std()
dataset['Age'] = dataset['Age'].replace(
    to_replace=0, value=median_Age)


from sklearn.preprocessing import MinMaxScaler as Normalizer

scaler = Scaler()
scaler.fit(x)
train_set_scaled = scaler.transform(x)

datafram = pd.DataFrame(data=train_set_scaled)
#datafram.to_csv("diabetes_impute_normalization_std.csv", index=False, encoding="utf-8")


C:\Users\Nazmus Sakib\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [32]:
train_set, test_set = train_test_split(
    dataset, test_size=0.2, random_state=42)

train_set_labels = train_set["Outcome"].copy()
train_set = train_set.drop("Outcome", axis=1)

test_set_labels = test_set["Outcome"].copy()
test_set = test_set.drop("Outcome", axis=1)

In [33]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer()
scaler.fit(train_set)
train_set_scaled = scaler.transform(train_set)
test_set_scaled = scaler.transform(test_set)

df = pd.DataFrame(data=train_set_scaled)
df.head()

0         1         2         3         4         5         6  \
0  0.013648  0.573228  0.132087  0.108860  0.786441  0.053803  0.002075   
1  0.047106  0.586210  0.429190  0.125616  0.603189  0.147599  0.006710   
2  0.005774  0.802569  0.265598  0.109704  0.479232  0.165710  0.003776   
3  0.000000  0.745328  0.231468  0.073849  0.533507  0.101383  0.001176   
4  0.014686  0.327991  0.195815  0.090565  0.905646  0.113083  0.000583   

          7  
0  0.143307  
1  0.261701  
2  0.127025  
3  0.300909  
4  0.112594

In [34]:
#df.to_csv("diabetes_impute_normalizer.csv", index=False, encoding="utf-8")

In [35]:
dataset = numpy.loadtxt("diabetes_impute_normalization_std.txt", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]


model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [36]:
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

Epoch 1/100
768/768 [==============================] - 1s 2ms/step - loss: 0.6801 - acc: 0.5977
Epoch 2/100
768/768 [==============================] - 0s 183us/step - loss: 0.6401 - acc: 0.6510
Epoch 3/100
768/768 [==============================] - 0s 203us/step - loss: 0.6115 - acc: 0.6510
Epoch 4/100
768/768 [==============================] - 0s 203us/step - loss: 0.5931 - acc: 0.6510
Epoch 5/100
768/768 [==============================] - 0s 203us/step - loss: 0.5611 - acc: 0.7214
Epoch 6/100
768/768 [==============================] - 0s 203us/step - loss: 0.5323 - acc: 0.7448
Epoch 7/100
768/768 [==============================] - 0s 203us/step - loss: 0.5094 - acc: 0.7591
Epoch 8/100
768/768 [==============================] - 0s 183us/step - loss: 0.4997 - acc: 0.7591
Epoch 9/100
768/768 [==============================] - 0s 203us/step - loss: 0.4911 - acc: 0.7604
Epoch 10/100
768/768 [==============================] - 0s 203us/step - loss: 0.4845 - acc: 0.7604
Epoch 11/100
768/768 

In [37]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))
end = time.time()
print(end - start)

768/768 [==============================] - 0s 387us/step

acc: 80.4688%
22.591076612472534


## impute&normalization PCA

In [3]:
from sklearn.decomposition import PCA

start = time.time()


In [39]:
dataset = numpy.loadtxt("diabetes_impute_normalization_std.txt", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]

In [40]:
pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)

[[ 0.32848414  0.04767619]
 [-0.22643479 -0.10992424]
 [ 0.23699816  0.07104916]
 ...
 [-0.00726968 -0.08620371]
 [ 0.02014254 -0.02871416]
 [-0.27715052 -0.02236748]]


In [9]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, batch_size=10)

ValueError: Error when checking input: expected dense_16_input to have shape (8,) but got array with shape (7,)

In [42]:
scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))
end = time.time()
print(end - start)

768/768 [==============================] - 0s 365us/step

acc: 79.8177%
20.445217847824097


## feature testing

### without bloodpressure

In [10]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_bloodpressure.txt", delimiter=",")

X = dataset[:,0:7]
Y = dataset[:,7]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[ 0.33156191  0.07402733]
 [-0.22132405 -0.12891123]
 [ 0.26745423  0.12850989]
 ...
 [-0.00732415 -0.08887756]
 [ 0.04826286 -0.00317944]
 [-0.28788377 -0.05417924]]
Epoch 1/100
768/768 [==============================] - 2s 2ms/step - loss: 0.6235 - acc: 0.7109
Epoch 2/100
768/768 [==============================] - 0s 241us/step - loss: 0.5285 - acc: 0.7396
Epoch 3/100
768/768 [==============================] - 0s 261us/step - loss: 0.4969 - acc: 0.7513
Epoch 4/100
768/768 [==============================] - 0s 261us/step - loss: 0.4901 - acc: 0.7539
Epoch 5/100
768/768 [==============================] - 0s 220us/step - loss: 0.4869 - acc: 0.7565
Epoch 6/100
768/768 [==============================] - 0s 261us/step - loss: 0.4857 - acc: 0.7591
Epoch 7/100
768/768 [==============================] - 0s 212us/step - loss: 0.4846 - acc: 0.7682
Epoch 8/100
768/768 [==============================] - 0s 200us/step - loss: 0.4837 - acc: 0.7656
Epoch 9/100
768/768 [=============================

768/768 [==============================] - 0s 171us/step - loss: 0.4768 - acc: 0.7552
Epoch 82/100
768/768 [==============================] - 0s 151us/step - loss: 0.4762 - acc: 0.7630
Epoch 83/100
768/768 [==============================] - 0s 151us/step - loss: 0.4761 - acc: 0.7604
Epoch 84/100
768/768 [==============================] - 0s 139us/step - loss: 0.4753 - acc: 0.7617
Epoch 85/100
768/768 [==============================] - 0s 151us/step - loss: 0.4759 - acc: 0.7643
Epoch 86/100
768/768 [==============================] - 0s 151us/step - loss: 0.4753 - acc: 0.7643
Epoch 87/100
768/768 [==============================] - 0s 171us/step - loss: 0.4755 - acc: 0.7565
Epoch 88/100
768/768 [==============================] - 0s 151us/step - loss: 0.4776 - acc: 0.7682
Epoch 89/100
768/768 [==============================] - 0s 139us/step - loss: 0.4750 - acc: 0.7617
Epoch 90/100
768/768 [==============================] - 0s 151us/step - loss: 0.4752 - acc: 0.7630
Epoch 91/100
768/768 [=

### without SkinThickness and bloodpressure

In [11]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_bloodpressure_skinness.txt", delimiter=",")

X = dataset[:,0:6]
Y = dataset[:,6]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[ 0.32871259  0.05586229]
 [-0.22152933 -0.14204061]
 [ 0.2699094   0.17365834]
 ...
 [-0.0059357  -0.07882997]
 [ 0.05111037  0.03032706]
 [-0.28920874 -0.07454613]]
Epoch 1/100
768/768 [==============================] - 2s 3ms/step - loss: 0.6796 - acc: 0.6966
Epoch 2/100
768/768 [==============================] - 0s 219us/step - loss: 0.6332 - acc: 0.7435
Epoch 3/100
768/768 [==============================] - 0s 203us/step - loss: 0.5645 - acc: 0.7487
Epoch 4/100
768/768 [==============================] - 0s 192us/step - loss: 0.5180 - acc: 0.7513
Epoch 5/100
768/768 [==============================] - 0s 200us/step - loss: 0.5036 - acc: 0.7500
Epoch 6/100
768/768 [==============================] - 0s 212us/step - loss: 0.4983 - acc: 0.7552
Epoch 7/100
768/768 [==============================] - 0s 180us/step - loss: 0.4979 - acc: 0.7552
Epoch 8/100
768/768 [==============================] - 0s 192us/step - loss: 0.4961 - acc: 0.7539
Epoch 9/100
768/768 [=============================

768/768 [==============================] - 0s 171us/step - loss: 0.4797 - acc: 0.7539
Epoch 82/100
768/768 [==============================] - 0s 171us/step - loss: 0.4795 - acc: 0.7539
Epoch 83/100
768/768 [==============================] - 0s 200us/step - loss: 0.4801 - acc: 0.7513
Epoch 84/100
768/768 [==============================] - 0s 261us/step - loss: 0.4794 - acc: 0.7565
Epoch 85/100
768/768 [==============================] - 0s 220us/step - loss: 0.4796 - acc: 0.7552
Epoch 86/100
768/768 [==============================] - 0s 232us/step - loss: 0.4789 - acc: 0.7591
Epoch 87/100
768/768 [==============================] - 0s 261us/step - loss: 0.4792 - acc: 0.7539
Epoch 88/100
768/768 [==============================] - 0s 261us/step - loss: 0.4792 - acc: 0.7565
Epoch 89/100
768/768 [==============================] - 0s 261us/step - loss: 0.4792 - acc: 0.7591
Epoch 90/100
768/768 [==============================] - 0s 200us/step - loss: 0.4794 - acc: 0.7565
Epoch 91/100
768/768 [=

### without SkinThickness and bloodpressure and insuilin

In [12]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_bloodpressure_skinness_insulin.txt", delimiter=",")

X = dataset[:,0:5]
Y = dataset[:,5]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[ 0.33047851  0.08209394]
 [-0.21675473 -0.14975132]
 [ 0.26842772  0.19856396]
 ...
 [-0.00193256 -0.07505384]
 [ 0.05280656  0.04378335]
 [-0.28633215 -0.08402202]]
Epoch 1/100
768/768 [==============================] - 1s 2ms/step - loss: 0.6506 - acc: 0.6263
Epoch 2/100
768/768 [==============================] - ETA: 0s - loss: 0.5830 - acc: 0.657 - 0s 241us/step - loss: 0.5777 - acc: 0.6576
Epoch 3/100
768/768 [==============================] - 0s 192us/step - loss: 0.5312 - acc: 0.7435
Epoch 4/100
768/768 [==============================] - 0s 180us/step - loss: 0.5045 - acc: 0.7526
Epoch 5/100
768/768 [==============================] - 0s 212us/step - loss: 0.4952 - acc: 0.7513
Epoch 6/100
768/768 [==============================] - 0s 180us/step - loss: 0.4895 - acc: 0.7487
Epoch 7/100
768/768 [==============================] - 0s 212us/step - loss: 0.4865 - acc: 0.7565
Epoch 8/100
768/768 [==============================] - 0s 200us/step - loss: 0.4853 - acc: 0.7526
Epoch 9/100


768/768 [==============================] - 0s 212us/step - loss: 0.4767 - acc: 0.7578
Epoch 82/100
768/768 [==============================] - 0s 200us/step - loss: 0.4756 - acc: 0.7591
Epoch 83/100
768/768 [==============================] - 0s 192us/step - loss: 0.4761 - acc: 0.7552
Epoch 84/100
768/768 [==============================] - 0s 220us/step - loss: 0.4758 - acc: 0.7591
Epoch 85/100
768/768 [==============================] - 0s 192us/step - loss: 0.4760 - acc: 0.7617
Epoch 86/100
768/768 [==============================] - 0s 200us/step - loss: 0.4762 - acc: 0.7630
Epoch 87/100
768/768 [==============================] - 0s 212us/step - loss: 0.4754 - acc: 0.7578
Epoch 88/100
768/768 [==============================] - 0s 180us/step - loss: 0.4761 - acc: 0.7643
Epoch 89/100
768/768 [==============================] - 0s 151us/step - loss: 0.4764 - acc: 0.7565
Epoch 90/100
768/768 [==============================] - 0s 200us/step - loss: 0.4754 - acc: 0.7565
Epoch 91/100
768/768 [=

### without SkinThickness and bloodpressure and insuilin and diabetesFuncation

In [13]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_diabetesprectionfuncation.txt", delimiter=",")

X = dataset[:,0:4]
Y = dataset[:,4]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[ 0.32810897  0.07070331]
 [-0.2144913  -0.14406483]
 [ 0.26515485  0.19245054]
 ...
 [ 0.00164768 -0.0477599 ]
 [ 0.05427564  0.06053743]
 [-0.2839358  -0.07253812]]
Epoch 1/100
768/768 [==============================] - 1s 2ms/step - loss: 0.6754 - acc: 0.6445
Epoch 2/100
768/768 [==============================] - 0s 220us/step - loss: 0.6028 - acc: 0.6549
Epoch 3/100
768/768 [==============================] - 0s 220us/step - loss: 0.5336 - acc: 0.7279
Epoch 4/100
768/768 [==============================] - 0s 232us/step - loss: 0.5047 - acc: 0.7500
Epoch 5/100
768/768 [==============================] - 0s 200us/step - loss: 0.4960 - acc: 0.7474
Epoch 6/100
768/768 [==============================] - 0s 192us/step - loss: 0.4925 - acc: 0.7474
Epoch 7/100
768/768 [==============================] - 0s 200us/step - loss: 0.4924 - acc: 0.7500
Epoch 8/100
768/768 [==============================] - 0s 192us/step - loss: 0.4897 - acc: 0.7500
Epoch 9/100
768/768 [=============================

768/768 [==============================] - 0s 220us/step - loss: 0.4801 - acc: 0.7552
Epoch 82/100
768/768 [==============================] - 0s 192us/step - loss: 0.4807 - acc: 0.7578
Epoch 83/100
768/768 [==============================] - 0s 180us/step - loss: 0.4803 - acc: 0.7526
Epoch 84/100
768/768 [==============================] - 0s 212us/step - loss: 0.4789 - acc: 0.7513
Epoch 85/100
768/768 [==============================] - 0s 180us/step - loss: 0.4793 - acc: 0.7487
Epoch 86/100
768/768 [==============================] - 0s 171us/step - loss: 0.4801 - acc: 0.7591
Epoch 87/100
768/768 [==============================] - 0s 200us/step - loss: 0.4794 - acc: 0.7552
Epoch 88/100
768/768 [==============================] - 0s 171us/step - loss: 0.4793 - acc: 0.7552
Epoch 89/100
768/768 [==============================] - 0s 192us/step - loss: 0.4796 - acc: 0.7474
Epoch 90/100
768/768 [==============================] - 0s 200us/step - loss: 0.4796 - acc: 0.7552
Epoch 91/100
768/768 [=

### without SkinThickness and bloodpressure and insuilin and diabetesFuncation and pregnencis

In [14]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_pregnancies.txt", delimiter=",")

X = dataset[:,0:3]
Y = dataset[:,3]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[ 0.31638213  0.06700722]
 [-0.18224975  0.15068438]
 [ 0.20809719 -0.23127169]
 ...
 [-0.05391107 -0.00850498]
 [ 0.18478857  0.14136734]
 [-0.24102587  0.01126602]]
Epoch 1/100
768/768 [==============================] - 1s 2ms/step - loss: 0.6132 - acc: 0.6628
Epoch 2/100
768/768 [==============================] - 0s 220us/step - loss: 0.5350 - acc: 0.7357
Epoch 3/100
768/768 [==============================] - 0s 261us/step - loss: 0.5009 - acc: 0.7630
Epoch 4/100
768/768 [==============================] - 0s 241us/step - loss: 0.4894 - acc: 0.7617
Epoch 5/100
768/768 [==============================] - 0s 192us/step - loss: 0.4846 - acc: 0.7630
Epoch 6/100
768/768 [==============================] - 0s 220us/step - loss: 0.4823 - acc: 0.7643
Epoch 7/100
768/768 [==============================] - 0s 192us/step - loss: 0.4805 - acc: 0.7734
Epoch 8/100
768/768 [==============================] - 0s 200us/step - loss: 0.4801 - acc: 0.7604
Epoch 9/100
768/768 [=============================

768/768 [==============================] - 0s 261us/step - loss: 0.4704 - acc: 0.7669
Epoch 83/100
768/768 [==============================] - 0s 180us/step - loss: 0.4706 - acc: 0.7643
Epoch 84/100
768/768 [==============================] - 0s 191us/step - loss: 0.4707 - acc: 0.7708
Epoch 85/100
768/768 [==============================] - 0s 200us/step - loss: 0.4721 - acc: 0.7656
Epoch 86/100
768/768 [==============================] - 0s 192us/step - loss: 0.4700 - acc: 0.7708
Epoch 87/100
768/768 [==============================] - 0s 180us/step - loss: 0.4712 - acc: 0.7643
Epoch 88/100
768/768 [==============================] - 0s 192us/step - loss: 0.4717 - acc: 0.7669
Epoch 89/100
768/768 [==============================] - 0s 200us/step - loss: 0.4692 - acc: 0.7669
Epoch 90/100
768/768 [==============================] - 0s 192us/step - loss: 0.4718 - acc: 0.7695
Epoch 91/100
768/768 [==============================] - 0s 171us/step - loss: 0.4707 - acc: 0.7630
Epoch 92/100
768/768 [=

### without  age

In [15]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_age.txt", delimiter=",")

X = dataset[:,0:2]
Y = dataset[:,2]



pca = PCA(n_components=2).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(train_set, Y, epochs=100, batch_size=10)

scores = model.evaluate(train_set, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[-0.1621273  -0.01685487]
 [ 0.2327525  -0.03450266]
 [-0.32012554 -0.23866873]
 ...
 [ 0.02614077 -0.09624342]
 [-0.01966656 -0.04024838]
 [ 0.17001591  0.01525906]]
Epoch 1/100
768/768 [==============================] - 2s 2ms/step - loss: 0.6621 - acc: 0.6172
Epoch 2/100
768/768 [==============================] - 0s 232us/step - loss: 0.5751 - acc: 0.7318
Epoch 3/100
768/768 [==============================] - 0s 241us/step - loss: 0.5212 - acc: 0.7591
Epoch 4/100
768/768 [==============================] - 0s 220us/step - loss: 0.5047 - acc: 0.7643
Epoch 5/100
768/768 [==============================] - 0s 192us/step - loss: 0.5014 - acc: 0.7669
Epoch 6/100
768/768 [==============================] - 0s 200us/step - loss: 0.4990 - acc: 0.7656
Epoch 7/100
768/768 [==============================] - 0s 192us/step - loss: 0.4997 - acc: 0.7617
Epoch 8/100
768/768 [==============================] - 0s 180us/step - loss: 0.4986 - acc: 0.7682
Epoch 9/100
768/768 [=============================

768/768 [==============================] - 0s 180us/step - loss: 0.4816 - acc: 0.7656
Epoch 83/100
768/768 [==============================] - 0s 171us/step - loss: 0.4818 - acc: 0.7643
Epoch 84/100
768/768 [==============================] - 0s 200us/step - loss: 0.4807 - acc: 0.7695
Epoch 85/100
768/768 [==============================] - 0s 192us/step - loss: 0.4821 - acc: 0.7734
Epoch 86/100
768/768 [==============================] - 0s 171us/step - loss: 0.4825 - acc: 0.7669
Epoch 87/100
768/768 [==============================] - 0s 159us/step - loss: 0.4816 - acc: 0.7669
Epoch 88/100
768/768 [==============================] - 0s 192us/step - loss: 0.4817 - acc: 0.7617
Epoch 89/100
768/768 [==============================] - 0s 180us/step - loss: 0.4826 - acc: 0.7591
Epoch 90/100
768/768 [==============================] - 0s 171us/step - loss: 0.4790 - acc: 0.7695
Epoch 91/100
768/768 [==============================] - 0s 171us/step - loss: 0.4827 - acc: 0.7591
Epoch 92/100
768/768 [=

### without BMI

In [23]:
dataset = numpy.loadtxt("diabetes_std_impute_scaling_age_bmi.txt", delimiter=",")

X = dataset[:,0:1]
Y = dataset[:,1]



pca = PCA(n_components=1).fit(X)
train_set = pca.transform(X)

print(train_set)



model = Sequential()
model.add(Dense(12, input_dim=1, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


model.compile(loss='binary_crossentropy', optimizer='Nadam', metrics=['accuracy'])
model.fit(X, Y, epochs=250, batch_size=10)

scores = model.evaluate(X, Y)
print("\n%s: %.4f%%" % (model.metrics_names[1], scores[1]*100))

[[-0.16103536]
 [ 0.21614831]
 [-0.37058184]
 [ 0.19220014]
 [-0.09517789]
 [ 0.03055   ]
 [ 0.25805761]
 [ 0.03653704]
 [-0.45440043]
 [-0.02333338]
 [ 0.06647225]
 [-0.2807762 ]
 [-0.10715197]
 [-0.40650409]
 [-0.26880212]
 [ 0.12634268]
 [ 0.01857591]
 [ 0.08443338]
 [ 0.10838155]
 [ 0.03653704]
 [-0.02932042]
 [ 0.13232972]
 [-0.44841339]
 [ 0.01258887]
 [-0.13110014]
 [-0.02333338]
 [-0.15504831]
 [ 0.1443038 ]
 [-0.14307423]
 [ 0.02456296]
 [ 0.07245929]
 [-0.22090578]
 [ 0.19818718]
 [ 0.17423901]
 [-0.00537226]
 [ 0.10838155]
 [-0.10116493]
 [ 0.11436859]
 [ 0.1862131 ]
 [ 0.06048521]
 [-0.35262071]
 [-0.07122972]
 [ 0.09042042]
 [-0.29873733]
 [-0.22689282]
 [-0.35262071]
 [-0.14906127]
 [ 0.2999669 ]
 [ 0.10838155]
 [ 0.09640746]
 [ 0.10838155]
 [ 0.12035563]
 [ 0.19818718]
 [-0.32867254]
 [-0.17300944]
 [ 0.28799282]
 [-0.39453   ]
 [ 0.12634268]
 [-0.14906127]
 [ 0.09640746]
 [ 0.22213535]
 [-0.07122972]
 [ 0.46161704]
 [-0.11912606]
 [ 0.04252408]
 [ 0.13232972]
 [ 0.07245

Epoch 1/250
768/768 [==============================] - 2s 3ms/step - loss: 0.6789 - acc: 0.6510
Epoch 2/250
768/768 [==============================] - 0s 200us/step - loss: 0.6593 - acc: 0.6510
Epoch 3/250
768/768 [==============================] - 0s 212us/step - loss: 0.6506 - acc: 0.6510
Epoch 4/250
768/768 [==============================] - 0s 200us/step - loss: 0.6434 - acc: 0.6510
Epoch 5/250
768/768 [==============================] - 0s 212us/step - loss: 0.6356 - acc: 0.6510
Epoch 6/250
768/768 [==============================] - 0s 200us/step - loss: 0.6242 - acc: 0.6510
Epoch 7/250
768/768 [==============================] - 0s 192us/step - loss: 0.6109 - acc: 0.6510
Epoch 8/250
768/768 [==============================] - 0s 220us/step - loss: 0.5966 - acc: 0.6693
Epoch 9/250
768/768 [==============================] - 0s 200us/step - loss: 0.5826 - acc: 0.6992
Epoch 10/250
768/768 [==============================] - 0s 192us/step - loss: 0.5657 - acc: 0.7357
Epoch 11/250
768/768 

768/768 [==============================] - 0s 200us/step - loss: 0.5216 - acc: 0.7422
Epoch 84/250
768/768 [==============================] - 0s 192us/step - loss: 0.5205 - acc: 0.7500
Epoch 85/250
768/768 [==============================] - 0s 200us/step - loss: 0.5224 - acc: 0.7396
Epoch 86/250
768/768 [==============================] - 0s 212us/step - loss: 0.5209 - acc: 0.7487
Epoch 87/250
768/768 [==============================] - 0s 200us/step - loss: 0.5204 - acc: 0.7396
Epoch 88/250
768/768 [==============================] - 0s 192us/step - loss: 0.5238 - acc: 0.7409
Epoch 89/250
768/768 [==============================] - 0s 180us/step - loss: 0.5221 - acc: 0.7448
Epoch 90/250
768/768 [==============================] - 0s 212us/step - loss: 0.5206 - acc: 0.7474
Epoch 91/250
768/768 [==============================] - 0s 220us/step - loss: 0.5212 - acc: 0.7435
Epoch 92/250
768/768 [==============================] - 0s 192us/step - loss: 0.5209 - acc: 0.7409
Epoch 93/250
768/768 [=

768/768 [==============================] - 0s 200us/step - loss: 0.5225 - acc: 0.7409
Epoch 165/250
768/768 [==============================] - 0s 200us/step - loss: 0.5217 - acc: 0.7448
Epoch 166/250
768/768 [==============================] - 0s 232us/step - loss: 0.5214 - acc: 0.7474
Epoch 167/250
768/768 [==============================] - 0s 200us/step - loss: 0.5210 - acc: 0.7461
Epoch 168/250
768/768 [==============================] - 0s 200us/step - loss: 0.5202 - acc: 0.7409
Epoch 169/250
768/768 [==============================] - 0s 241us/step - loss: 0.5217 - acc: 0.7448
Epoch 170/250
768/768 [==============================] - ETA: 0s - loss: 0.5056 - acc: 0.756 - 0s 212us/step - loss: 0.5211 - acc: 0.7461
Epoch 171/250
768/768 [==============================] - 0s 200us/step - loss: 0.5205 - acc: 0.7409
Epoch 172/250
768/768 [==============================] - 0s 212us/step - loss: 0.5223 - acc: 0.7435
Epoch 173/250
768/768 [==============================] - 0s 220us/step - los

768/768 [==============================] - 0s 241us/step - loss: 0.5212 - acc: 0.7487
Epoch 246/250
768/768 [==============================] - 0s 220us/step - loss: 0.5211 - acc: 0.7422
Epoch 247/250
768/768 [==============================] - 0s 212us/step - loss: 0.5202 - acc: 0.7487
Epoch 248/250
768/768 [==============================] - 0s 220us/step - loss: 0.5213 - acc: 0.7370
Epoch 249/250
768/768 [==============================] - 0s 212us/step - loss: 0.5208 - acc: 0.7461
Epoch 250/250
768/768 [==============================] - 1s 722us/step

acc: 74.6094%
